### ISSUE TITLE
Link to invoice templates documentation is a dead link

### ISSUE THREAD

**Issue by ctp-placebo** [kimai/invoice-templates#1]
Link to invoice templates documentation ( http://www.kimai.org/documentation/developer/invoice-templates.html ) is a dead link on this page [here](https://github.com/kimai/invoice-templates)

**Comment by simonschaufi** [comment]
fixed with https://github.com/kimai/invoice-templates/commit/51b58908137952fcc77f6ac53320c2183a56edb2
