### ISSUE TITLE
Due Date

### ISSUE THREAD

**Issue by s3ppo** [kimai/invoice-templates#11]
Hi!

in Kimai its possible to change invoice date. in my opinion the due date should be invoice date + payment term.

at the moment its today + payment term.

pls correct me if i am wrong :)

best regards
Harald

**Comment by kevinpapst** [comment]
You are correct and yes, you found a bug.
Will be fixed with the next minor release: https://github.com/kimai/kimai/pull/4178

I am closing here now, because I forget it otherwise when I create the release.
