### ISSUE TITLE
A few missing variables like project.comment

### ISSUE THREAD

**Issue by Regnalf** [kimai/invoice-templates#14]
I am in the process of creating a docx template and would like to output the project description.

Unfortunately, this is not output in the final docx. With the help of the debug template I could see that it exists. However, the placeholder remains in the final document.

Both variables are actually filled, project.comment and query.project.comment.
Debug HTML
![screenshot_ 2023-12-29 um 17 21 33](https://github.com/kimai/invoice-templates/assets/43412166/4bf6a769-a639-4174-8da7-04647810e861)

Final Docx:
![screenshot_ 2023-12-29 um 17 22 30](https://github.com/kimai/invoice-templates/assets/43412166/648ed177-de3b-49af-9471-37bf4153c6d0)

**Comment by kevinpapst** [comment]
Impossible to help without seeing more of the template.

See https://www.kimai.org/documentation/invoices.html#project-variables

> If more than one project was found, you will have further variables (same list as above) called ${project.1.name}, ${project.2.name} and so on. The order is not guaranteed, so it is not recommended relying on those variables. If your template relies on a {$project.X} variable, it is recommended to limit the invoice data with the project search filter.

Do not rely on that variable, it depends on the query and the found data.

All templates use the same logic to generate and fill these variables, so if it works with debug, it works with docx.

**Comment by Regnalf** [comment]
I have tried it with and without filters, and with the same filter settings the data is included in the debug HTML and not in the docx. Or at least, it is not been converted.

Here is my template
[Rechnung2024.docx](https://github.com/kimai/invoice-templates/files/13797600/Rechnung2024.docx)

The grouping is set to Standard.
![screenshot_ 2023-12-30 um 10 12 40](https://github.com/kimai/invoice-templates/assets/43412166/a8a48065-5bfb-4790-858a-5ae98773d310)

**Comment by Regnalf** [comment]
Intersting thing is, if you place both lines right under each other

![screenshot_ 2024-01-10 um 09 45 52](https://github.com/kimai/invoice-templates/assets/43412166/0edd62f1-1573-452e-829c-23716d0b1aa6)


the first will be replaced with the project description.

![screenshot_ 2024-01-10 um 09 42 51](https://github.com/kimai/invoice-templates/assets/43412166/71b4906b-2194-4610-9a9d-6a88c1329864)

If there is only one placeholder, no change will happen.

**Comment by kevinpapst** [comment]
Then you probably have unvisible formatting characters in the variable.

But under the hood a DOCX is a XML document, which could like this:
```xml
<text><bold>${query.project</bold><bold>.comment}</bold></text>
```

Kimai will search for the exact string to be replaced and in that above example the replacer is not visible to Kimai. Instead it needs to be:
```xml
<text><bold>${query.project.comment}</bold></text>
```

Create a new docx. Add these variables. DO NOT change or add any styling. Test with this docx if the variables are now replaced.

Usually you can fix such problems by selecting the row, removing all formattings. Retesting with carefully added formattings.

**Comment by Regnalf** [comment]
Yes, you were right. There was a control character for an object anchor, as you can see in one of my first screenshots. 
I used pages from macos to create the template and then exported it as docx. Only in this docx was this control character visible.

I edited the docx afterwards and it now works when the control character is outside. (the blue line with circle on top)

![screenshot_ 2024-01-11 um 07 48 44](https://github.com/kimai/invoice-templates/assets/43412166/86139abc-89f6-47a1-8b98-cdaba777e6ea)

But it is a bit strange that it was exactly set inside of this variable, at least not by me!

**Comment by kevinpapst** [comment]
Aha, and I though that is the cursor. Missed it initially.
Glad we could solve it!
