### ISSUE TITLE
uploading templates

### ISSUE THREAD

**Issue by montarion** [kimai/invoice-templates#16]
uploading invoice templates doesn't allow for pdf or html templates, even though the documentation says those are supported.

![image](https://github.com/kimai/invoice-templates/assets/7190683/eed6d2c8-e4e0-466d-8183-5a9204cc1918)

**Comment by kevinpapst** [comment]
Thanks for reading the docs 👍 

Now read it again: https://www.kimai.org/documentation/invoices.html#create-your-own-invoice-document

<img width="909" alt="Bildschirmfoto 2024-04-21 um 22 22 30" src="https://github.com/kimai/invoice-templates/assets/533162/18c00fdb-915c-4fd4-8839-48ad91fb6608">

Please use this place for support: https://github.com/kimai/kimai/discussions
