### ISSUE TITLE
Where to find the invoice folder in docker installation

### ISSUE THREAD

**Issue by ThomasKoscheck** [kimai/invoice-templates#2]
Hello,
I can't find the `extensions/ki_invoice/invoices/` in the var folder in my default docker installation.

May you help me?

Kind regards
Thomas

**Comment by kevinpapst** [comment]
Afaik there is no docker for Kimai 1.

**Comment by ThomasKoscheck** [comment]
So this doesn't work for kimai2?

**Comment by kevinpapst** [comment]
Nope. Here are examples for Kimai 2
https://github.com/Keleo/kimai2-invoice-templates
