### ISSUE TITLE
bug at invoice_grouped_by_project

### ISSUE THREAD

**Issue by s3ppo** [kimai/invoice-templates#8]
hi there is a bug (also on the screenshot of the repo) with the due_date in the text.

its the same variable like the one in the header, but the value is always today and not the due_date.

![image](https://github.com/kimai/invoice-templates/assets/17125438/0b56be60-6b1d-48e1-948b-a48b717d5061)

**Comment by kevinpapst** [comment]
ping @aroesler-privat

**Comment by aroesler-privat** [comment]
Hi,

I just created a pull request. @kevinpapst , did this work out? Looks kind of strange in my profile :-/.

Greetings,

Andreas

**Comment by kevinpapst** [comment]
Fixed by @aroesler-privat in https://github.com/kimai/invoice-templates/commit/459386287605af41ec28ada479eb7b9f6c83614d

Thanks Andreas for the speedy fix 👍

**Comment by s3ppo** [comment]
Vielen dank jungs. Und das am sonntag 🥳👍
